version: "3"

vars:
  APP_NAME: "jetimer"
  BUNDLE_BASE: "bundles"

tasks:
  build:
    desc: "Build and package the project"
    silent: true
    vars:
      VERSION:
        sh: cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version'
    cmds:
      # Create folders
      - mkdir -p {{.BUNDLE_BASE}}/{{.VERSION}}

      # Build
      - cargo build --release

      # Clean binary
      - strip target/release/{{.APP_NAME}}

      # Package
      - tar -cvzf {{.BUNDLE_BASE}}/{{.VERSION}}/{{.APP_NAME}}-v{{.VERSION}}-x86_64-linux-universal.tar.gz -C target/release {{.APP_NAME}}
      - tar -cvJf {{.BUNDLE_BASE}}/{{.VERSION}}/{{.APP_NAME}}-v{{.VERSION}}-x86_64-linux-universal.tar.xz -C target/release {{.APP_NAME}}

      - echo "Build completed for version {{.VERSION}}"
